// <auto-generated />
namespace CardSystem.CMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PrivateKey1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PrivateKey1));
        
        string IMigrationMetadata.Id
        {
            get { return "201704191858103_PrivateKey1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
